### ISSUE TITLE
cp-permissions

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/dkhamsing.github.io#2]
# TODO
- [ ] delete `wip*` branches after merge https://github.com/dkhamsing/Cirrus-Insight-Mobile-iOS/commits/dev/permissions 
- [ ] integrate `ats`
- [ ] `off` case (remove instead of disable buttons)
  - iphone gridview
  -  ipad sidebar 
- [ ] prevent gridview dismiss when upselling
- [ ] find out what to do about email/link tracking and notifications

## not implemented in mobile yet
- [ ] `chatter_attachment_preference`
- [ ] `followup_reminder`
- [ ] `send_later`
- [ ] `signature extraction`

# list
- [x] "activities_list",
- [x] "add_to_salesforce",
- [x] "cases_list",
- [x] "create_records",
- [x] "edit_layout",
- [x] "email_attachments",
- [x] "email_templates",
- [x] "email_tracking",
- [x] ~~"full_snapshot",~~
- [x] "link_tracking",
- [x] "opportunities_list",
- [x] "quick_add_to_salesforce",
- [x] "related_lists",
- [x] "signature_extraction",
- [x] "edit_layout"
- [x] ~~"search",~~
- [x] "enhanced_search" 

## does not apply to mobile
- "case_assignment_rules_prompt": "off",
- "disable_event_color_sync": "off",
- "disable_private_event_sync": "off",
- "force_auto_log_compose": "off",
- "lead_assignment_rules_prompt": "off",
- "calendar_sync",
-  "calendar_ui",
-   "csrf_unit",
-  "mobile",
-   "my_tasks",
-   "compose_bar",
-    "contact_sync",
-  "customize_ci",
-   "dashboard",

# archive
- [x] work on iphone first
- [x] then look at ipad
- [x] `planinfo` has to be updated with new permissions object
- [x] create all permissions in plan info
- [x] each permission can take 3 states: on, off, upsell (enum)
- [x] verify yellow permissions
- [x] start with quick add and add to sales force
- [x] create record
- [x] full snapshot
- [x] lists (look at isRelatedListEnabled)
- [x] ipad: tap on grey pill (should do nothing)
- [x] when sending, check if ats and qats is on before showing send overlay
- [x] iphone: how to display cloud button
- [x] enhanced search = custom objects
- [x] `create_records` create AND edit
- [x] list and snapshot: remove from snapshot if permissions are off
- [x] undo above
- [x] remove full snap shot
- [x] email attachments 
- [x] ~~"chatter_attachment_preference",~~
- [x] upsell email tracking
- [x] upsell add to sf
- [x] upsell the rest
- [x] ~~integration with compose pills: ats,   email tracking,   email template~~
- [x] ~~default values if not returned from api?~~
- [x] planinfo is generated.. should everything move to category
- [x] fill out all upsell messages, how to get them
- [x] verify email tracking
- [x] `salesforce_link` 

# Reference
https://secure3.cirrusinsight.com/services/plan

`CPDataManager`
`updateOrCreateSingleObjectByClass`

https://cirruspath.atlassian.net/browse/IOS-318 
https://portal.isdev.info:8443/jira/browse/IPADCIRRUS-1346

https://free.dev.cirrusinsight.com/sfdcLogin.php 
https://free.dev.cirrusinsight.com/services/plan

**Comment by dkhamsing** [comment]
https://github.com/dkhamsing/work/issues/2
