### ISSUE TITLE
ci-todo

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/dkhamsing.github.io#3]
- [ ] csk implementation should handle revoked tokens
- [ ] after contact view merge, update link tracking buttons
- [ ] update email tracking header
- [ ] pull request w/ permissions

**Comment by dkhamsing** [comment]
https://github.com/dkhamsing/work/issues/1
